### ISSUE TITLE
should trim indent from the first line of copied/pasted block

### ISSUE THREAD

**Issue by lunelson** [shepelevstas/dumb-copy-paste#1]
This works very closely to Sublime's paste-and-indent but I notice one difference: if I copy an indented block by dragging a selection in the gutter, selecting entire lines, the pasted block will be indented by the position where I've pasted it PLUS however much the copied block was indented. The solution I believe, would be to note the indentation of the first line in the copied block, and subtract that from the indentation being applied. Any chance of this?

**Comment by shepelevstas** [comment]
Can you give an example here? In picture or code here

**Comment by lunelson** [comment]
Sure. In the following capture from sublime, I copy a block of code which is already indented by several spaces, and then place my cursor at a position indented another several spaces, and when I do sublime's indented paste my pasted block *starts exactly where I put the cursor*. Doing the same operation with your extension, the original indentation would also be kept, leaving the final block indented by the position of the cursor *plus* the copied block's original indentation.

![indented-paste](https://user-images.githubusercontent.com/1242864/49591977-32e01600-f970-11e8-94ae-1370f0c33b8d.gif)

**Comment by shepelevstas** [comment]
Thank you. Now I get it. I'll fix it next month, or month after the next, have no time for now=)

**Comment by shepelevstas** [comment]
Good News! Managed to scrape up couple hours to fix it!=D
